spring.application.name=kf-consumer-service


#kafka
service.kafka.server=localhost:9092
service.kafka.consumer.group = KConsGROUP
service.kafka.consumer.topic = global-channel-topic
service.kafka.consumer.concurrency= 3

server.port=8083


#mongo
spring.data.mongodb.uri=mongodb://localhost:2717/
spring.data.mongodb.database=RideSharing